=encoding utf-8

=head1 Saint-Petersburg perl-mongers

Да, это - СЕКТАААААА!!!!111

=head1 Some ideas

    Чего хочется от сайта (Дамп мозга :):

    * Perlgolf (http://cs.usu.edu.ru/langs/perl/)
    -- Расширить, углубить и осоциалить пункты 1, 5, 4, 9
    * Q&A (Вопросы и ответы) - hеализация  простой системы вопросов и ответов. Пользователь набирает вопрос по  Перлу или решению какой-либо проблемы, ему отвечают. У вопроса и у  ответа можно выставлять оценку. В принципе, хороший пример: q&a  хабрахабра.
    * Получение информации
    -- вакансии (статика) на первую (фид)!
        -- блок из ссылок на сайты с вакансиями
        -- трансляция rss-фидов
    -- мероприятия
        -- Шапка YAPC::TV (но зачем?!) (:
        -- Ссылка на Perl-календарь мероприятий
        -- Нормальный анонс Saint Perl - 2011 - Картиночка, баннерчик, прямоугольничег с описанием
    -- новости (или даже блог?!)
        -- нужен движок новостей )) Mojolicious, привет ))))
        -- Новости на глагне выводят всё: вакансии, вопросы, грядущие события и т.д. (сверху свежее)
    -- ссылки (добавить к существующим)
        -- на разные полезные Perl-ресурсы (Планета Перл...)
        -- на ИРКу (irc://irc.pm.org/#spb.pm)
    -- обновляемые ссылки (аналог секции "Не проходите мимо" на http://moscow.pm.org)
    -- нормальный лук для сайта :)
        -- смотрим, например, здесь http://twitter.github.com/bootstrap/
    * Социальная компонента
    -- рассылка spb.pm.org
        -- Форма E-Mail + кнопка "Подписаться"
        -- Ссылка на список подписчиков
        -- Ссылка на архивы рассылок
    -- официальные аккаунты в твиттере и других социальных сетях (LinkedIn группа! http://www.linkedin.com/groups/SPbPM-Saint-Petersburg-Perl-Mongers-3975598?gid=3975598&trk=hb_side_g )
    -- регистрация (или авторизация через Open** / ...) на сайте с заполнением профиля
    -- трансляция из ИРКи?! (на Index'e линк на отдельную страницу про ирц. На странице сообщается адрес сервера, каналы. + транслируются последние 5 сообщений из чатика, например);
    -- http-общение (веб-гейт до ИРКи?)
    -- конкурЗы! (кто на заднице напишет регулярку и сфотается?)

    #spb.pm  на irc.perl.org
    
    * аннонс saint perl
    -- придумать social программу (afterparty!!)

http://sync.in/qBXpMU7Z8R